[project]
name = "tree-classification-framework"
version = "0.1.0"
description = "Scripts and utilities for view-level tree classification"
authors = [
    {name = "David Russell",email = "djrussell@ucdavis.edu"}
]
license = "GPL-3.0-or-later"
requires-python = ">=3.12"
dependencies = [
    "geopandas (>=1.1.4,<2.0.0)",
    "imageio (>=2.37.4,<3.0.0)",
    "rasterio (>=1.5.1,<2.0.0)",
    "scipy (>=1.18.1,<2.0.0)",
    "tqdm (>=4.70.1,<5.0.0)",
    "pillow (>=12.3.0,<13.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"